# Generated by Django 3.2.15 on 2022-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailValidation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalidations',
            name='input_file',
            field=models.FileField(default='default.csv', help_text='xlsx and csv files only.', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='emailvalidations',
            name='rcpt_email',
            field=models.EmailField(blank=True, help_text='Email Field, max 255 characters.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailvalidations',
            name='taskName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
