# Generated by Django 3.2.15 on 2022-11-22 07:08

import D_Mart.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailValidation', '0002_auto_20220927_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidEmailExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Task name must be unique, cannot be blank!', max_length=255, unique=True)),
                ('supplier_emails_file', models.FileField(default='default.csv', help_text='Upload .csv files only, with column: email or download template for reference ', upload_to=D_Mart.utils.import_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('terminated', 'terminated'), ('completed', 'completed')], default='pending', max_length=100, verbose_name='Task Status')),
                ('executed_comments', models.TextField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_emails_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification Exports',
                'verbose_name_plural': 'Email Verification Export',
            },
        ),
    ]
