# Generated by Django 3.2.15 on 2022-08-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyNow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('appliances', 'Appliances'), ('clothing', 'Clothing'), ('toys', 'Toys'), ('beverages', 'Beverages'), ('grooming', 'Grooming'), ('others', 'Others')], default='Others', max_length=12),
        ),
    ]
