# Generated by Django 3.2.15 on 2022-08-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyNow', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('groceries', 'Groceries'), ('appliances', 'Appliances'), ('clothing', 'Clothing'), ('toys', 'Toys'), ('beverages', 'Beverages'), ('grooming', 'Grooming'), ('others', 'Others'), ('shoes', 'Shoes')], default='Others', max_length=12),
        ),
    ]
