# Generated by Django 3.2.15 on 2022-08-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuyNow', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Toys', 'Toys'), ('Beverages', 'Beverages'), ('Brooming', 'Grooming'), ('Others', 'Others'), ('Shoes', 'Shoes')], default='Others', max_length=12),
        ),
    ]
